### ISSUE TITLE
There are no commands defined in the "eav:media" namespace

### ISSUE THREAD

**Issue by cypher909** [magento-hackathon/module-eavcleaner-m2#1]
Hello, I'm running Magento 2.3.6 with PHP 7.3. I have tried making sure the module is enabled. Other commands show up and work just fine. Any advice for me?

**Comment by sprankhub** [comment]
How exactly did you install the module? When you run `bin/magento setup:upgrade`, does it show up in your `app/etc/config.php`?

**Comment by cypher909** [comment]
I have installed it via composer using the command in the readme. It does show in the config.php 'Hackathon_EAVCleaner' => 1,
I tried completely uninstalling it, removing it from the setup_module table and running cache:clean, cash:flush, setup:upgrade, then reinstalling it via composer and running setup:upgrade. It then shows in config.php but not in setup_module table.

**Comment by sprankhub** [comment]
Then I do not have any idea to be honest. It works flawlessly for me under 2.4.3. I do not see any reason why it should not work on 2.3.6 (although you should really update ^^).

**Comment by cypher909** [comment]
Ok thank you anyway. I am in the process of updating now and issue occurs with both 2.3.6 and 2.4.3. I will report back if I find a solution.

**Comment by Tjitse-E** [comment]
> I have installed it via composer using the command in the readme. It does show in the config.php 'Hackathon_EAVCleaner' => 1, I tried completely uninstalling it, removing it from the setup_module table and running cache:clean, cash:flush, setup:upgrade, then reinstalling it via composer and running setup:upgrade. It then shows in config.php but not in setup_module table.

It's correct that this module won't show in the `setup_module` table since it has no version in [module.xml](https://github.com/magento-hackathon/module-eavcleaner-m2/blob/main/etc/module.xml#L3), so no problems there.

You could try to run `php bin/magento setup:di:compile` to see if you have any errors in your DI config, that could cause this behaviour.

**Comment by cypher909** [comment]
Great suggestion about setup:di:compile. I did have an error in one of my custom extensions causing the issue. Thanks to you both for the help!

**Comment by sprankhub** [comment]
Glad that you could solve it, @cypher909!

Nice catch and debugging tip, @Tjitse-E!
