### ISSUE TITLE
Feature Request: Add --force command to eav:media:remove-unused

### ISSUE THREAD

**Issue by scotty0100** [magento-hackathon/module-eavcleaner-m2#14]
I added eav:media:remove-unused command to a cron due to how my Magento site adds products, it syncs up images nightly and wipes all product images with new ones. Magento leaves the old images on the hard disk so I want it to be cleaned up daily.

I added eav:media:remove-unused to a cron but because of the prompt I don't think it runs - I amended the vendor file to do this which works for me but am scared of it being overwritten in the future - hence the feature request! Otherwise I'll make a plugin to properly extend it.

```
protected function configure()
    {
        $this
            ->setName('eav:media:remove-unused')
            ->setDescription('Remove unused product images')
            ->addOption('dry-run')
			->addOption('force');
    }

```
 ```
   public function execute(InputInterface $input, OutputInterface $output): void
    {
        $fileSize   = 0;
        $countFiles = 0;
        $isDryRun   = $input->getOption('dry-run');
        $isForce   = $input->getOption('force');

        if (!$isDryRun && $input->isInteractive() && !$isForce) {
```

Adding a --force command would be useful for those who want this in a cron.

**Comment by peterjaap** [comment]
If you can do a PR, that'd be great!
