### ISSUE TITLE
Unused images are not deleted, because deleted products are still contained in catalog_product_entity_media_gallery

### ISSUE THREAD

**Issue by FlobeiGM** [magento-hackathon/module-eavcleaner-m2#15]
The command "eav:attributes:remove-unused" does not show any images to be deleted. This is because Magento does not delete the deleted products from the catalog_product_entity_media_gallery table. The table now has more than 20000 entries, even though our store only has just under 4000 products.
I found a similar error description here: https://magento.stackexchange.com/questions/238244/magento2-manage-and-understand-images-of-deleted-products-behavior

I am using Magento 2.3.7p3.

Does anyone have an idea what this is due to?

**Comment by peterjaap** [comment]
@FlobeiGM no idea why that happens, but have you tried this one? https://github.com/cap340/CleanMedia

**Comment by FlobeiGM** [comment]
@peterjaap thank you for your fast feedback! I have no idea why Magento doesn't clear the table correctly for us.
But we now use the following module and it works with it: https://github.com/hungersoft/magento2-image-clean.
