### ISSUE TITLE
Hackathon\EAVCleaner\Console\Command\RestoreUseDefaultValueCommand\Interceptor

### ISSUE THREAD

**Issue by mattyl** [magento-hackathon/module-eavcleaner-m2#19]
threw an error on setup:upgrade

soemthing about iteratorFactory

sorry removed plugin before properly copying error message

**Comment by sprankhub** [comment]
:joy: Not a very helpful issue, to be honest...

I just required the `main` branch in Magento 2.4.3 and ran `bin/magento setup:upgrade` without any issues. So I will close this for now. Feel free to re-open or create a new issue with details about the error.
