### ISSUE TITLE
Show all images for deletion.

### ISSUE THREAD

**Issue by teodorpav** [magento-hackathon/module-eavcleaner-m2#2]
Hi,
I ran it with --dry-run mode but it showed that it will delete all photos, not just those that are not in catalog_product_entity_media_gallery.

Magento 2.4.3-p1

**Comment by sprankhub** [comment]
So you say that it also showed images, which are still referenced in `catalog_product_entity_media_gallery`? That would be weird. Could you debug into this?

**Comment by teodorpav** [comment]
Hi,
I don't know how to debug it.
Here are the results:

https://prnt.sc/26i6cvo
https://prnt.sc/26i6d97
https://prnt.sc/26i6dkr

Thank you

**Comment by teodorpav** [comment]
By some reason some images are with URL with two // in catalog_product_entity_media_gallery.
Those images are uploaded from import products script and obviously there is a some problem.
https://prnt.sc/26i6rky
And the script can't detect this.
