### ISSUE TITLE
Error in tables

### ISSUE THREAD

**Issue by teodorpav** [magento-hackathon/module-eavcleaner-m2#3]
When I ran: bin/magento eav:attributes:remove-unused --dry-run

I receive:

In Mysql.php line 599:
                                                                                                                           
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ee.catalog_product_entity_static' doesn't exist, query was:   
  SELECT COUNT(*) FROM catalog_product_entity_static WHERE attribute_id = ?                                                
                                                                                                                           

In Mysql.php line 110:
                                                                                                                           
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ee.catalog_product_entity_static' doesn't exist, query was:   
  SELECT COUNT(*) FROM catalog_product_entity_static WHERE attribute_id = ?                                                
                                                                                                                           

In Mysql.php line 91:
                                                                                                              
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ee.catalog_product_entity_static' doesn't exist

**Comment by sprankhub** [comment]
Oh that is a good one! That would currently indeed happen for any attribute with backend type `static`, because we do not have a check for that. Would you be able to submit a PR for that?

**Comment by teodorpav** [comment]
Thank you.
I can't pull request.
If you can do this for me.

**Comment by sprankhub** [comment]
This has now been fixed.
