### ISSUE TITLE
Skip placeholder files

### ISSUE THREAD

**Issue by perryholden** [magento-hackathon/module-eavcleaner-m2#5]
When running `bin/magento eav:media:remove-unused --dry-run`, I see that the tool wants to remove placeholder images:

```
## WOULD REMOVE: /placeholder/default/photo-coming-soon3.jpg ##
## WOULD REMOVE: /placeholder/default/photo-coming-soon3_1.jpg ##
## WOULD REMOVE: /placeholder/default/photo-coming-soon3_2.jpg ##
## WOULD REMOVE: /placeholder/default/photo-coming-soon3_3.jpg ##
```

I would think we'd want to skip these, correct? Since they are referenced in `core_config_data`? If you agree, we can modify the console command class to skip `/placeholder` like you do `/cache`, as seen in `\Hackathon\EAVCleaner\Console\Command\RemoveUnusedMediaCommand::execute`:

```
    private function isInCachePath(?string $file): bool
    {
        return strpos($file, '/cache') !== false;
    }
```

If this makes sense to you, I can submit a PR, if needed.

**Comment by sprankhub** [comment]
We should definitely skip those, right! Happy to review and merge a PR.

Related: https://github.com/magento-hackathon/EAVCleaner/issues/29

**Comment by perryholden** [comment]
@sprankhub - Thanks. I tested my changes locally to ensure it behaved as I wanted.

**Comment by sprankhub** [comment]
Thanks, @perryholden!
