### ISSUE TITLE
Expand eav:config:restore-use-default-value command to also compare with default in config.xml

### ISSUE THREAD

**Issue by peterjaap** [magento-hackathon/module-eavcleaner-m2#7]

**Comment by fredden** [comment]
I've created #9 for `eav:config:restore-use-default-value`, to remove values from `core_config_data` table when they match the values set in `etc/config.xml`. This seems related to this issue, but the command mentioned here is `eav:attributes:restore-use-default-value`.

@peterjaap please can you provide an example of where an attribute would have a default value in `config.xml`?

**Comment by peterjaap** [comment]
@fredden sorry I meant the config one! Thanks so much for building this!

**Comment by fredden** [comment]
No problem. I'll update the wording on #9 so that it closes this when merged in.
